name: Generate SBOM

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CycloneDX locally
        run: npm install @cyclonedx/bom

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM and verify
        run: |
          npx bom -o sbom.json
          ls -la

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
