name: Generate SBOM

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CycloneDX tool
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Install project dependencies
        run: npm install

      - name: Generate SBOM
        run: cyclonedx-npm --output-format JSON --output-file sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
